"""
validators/rules.py

Validation rule implementations for the v1.7 Lite synthetic clinical dataset.

This module is intentionally deterministic and side-effect free.  It validates
patient dictionaries that were already generated by the data generation layer.
It does not generate data, repair records, write files, generate SOAP, create
chunks, call ChromaDB, or call any LLM.

Rules implemented here:
- V1  Chronological visit order
- V2  Allergy / medication contradiction
- V3  Impossible vitals and age bounds
- V4  Required fields and forbidden demographic age field
- V5  prior_visit_id integrity
- V6  Duplicate visit IDs
- V7  Enum validation, v1.7 Lite fields, and CKD co-occurrence rule
- V8  Date format validation
- V9  BP forbidden in labs and metadata-like structures
- V10 timeline_events field forbidden
- V11 Medication whitelist, route, frequency, status, and trajectory validation
- V12 Dataset diversity fingerprint and retrieval signature validation
- V13 Optional embedding similarity report helper, report-only
"""

from __future__ import annotations

import math
import re
from dataclasses import dataclass, field
from datetime import date, datetime
from itertools import combinations
from typing import Any, Iterable, Mapping, Sequence

from config.constants import (
    AGE_LIMITS,
    BP_FORBIDDEN_LAB_TERMS,
    BP_FORBIDDEN_METADATA_TERMS,
    CKD_ALLOWED_TIER,
    CKD_REQUIRED_CONDITIONS,
    CONDITIONS,
    CORE_SOURCE_TYPES,
    DATE_FORMAT,
    DATE_REGEX,
    EMBEDDING_MODEL_NAME,
    FLAGS,
    FORBIDDEN_CHROMA_METADATA_FIELDS_V17_LITE,
    FORBIDDEN_DEMOGRAPHICS_FIELDS,
    FORBIDDEN_VISIT_FIELDS,
    FREQUENCIES,
    LAB_TYPES,
    MEDICATION_NAMES,
    MEDICATION_STATUS,
    MEDICATION_TRAJECTORY_EVENTS,
    MEDICATION_WHITELIST,
    MIN_RETRIEVAL_INTENT_TAGS,
    MAX_RETRIEVAL_INTENT_TAGS,
    MINIMAL_CHROMA_METADATA_FIELDS_V17_LITE,
    OPTIONAL_CHROMA_METADATA_FIELDS_V17_LITE,
    PATIENT_ID_REGEX,
    PRIMARY_RETRIEVAL_TARGETS,
    REQUIRED_ALLERGY_FIELDS,
    REQUIRED_CLINICAL_EVENT_FIELDS,
    REQUIRED_DEMOGRAPHICS_FIELDS,
    REQUIRED_LAB_FIELDS,
    REQUIRED_MEDICATION_FIELDS,
    REQUIRED_PATIENT_METADATA_FIELDS_V17_LITE,
    REQUIRED_RETRIEVAL_CONTEXT_FIELDS,
    REQUIRED_TOP_LEVEL_FIELDS,
    REQUIRED_VISIT_FIELDS,
    REQUIRED_VITAL_FIELDS,
    RETRIEVAL_INTENT_TAGS,
    ROUTES,
    SEVERITIES,
    SEX_VALUES,
    SHORT_COURSE_MEDICATIONS,
    SOAP_SECTIONS,
    SOAP_STYLES,
    SOURCE_TYPES,
    SEMANTIC_FOCUS,
    TIERS,
    TIMELINE_PATTERNS,
    V13_SIMILARITY_CRITICAL_THRESHOLD,
    V13_SIMILARITY_WARN_THRESHOLD,
    VISIT_ID_REGEX,
    VISIT_ROLES,
    VISIT_TYPES,
    CLINICAL_EVENT_TYPES,
)


PatientRecord = dict[str, Any]
VisitRecord = dict[str, Any]
ValidationSeverity = str

FAIL: ValidationSeverity = "FAIL"
WARN: ValidationSeverity = "WARN"
INFO: ValidationSeverity = "INFO"
REPORT: ValidationSeverity = "REPORT"


@dataclass(frozen=True)
class ValidationIssue:
    """One validation finding produced by a rule."""

    rule_id: str
    severity: ValidationSeverity
    patient_id: str
    message: str
    path: str = ""
    context: dict[str, Any] = field(default_factory=dict)

    def as_dict(self) -> dict[str, Any]:
        return {
            "rule_id": self.rule_id,
            "severity": self.severity,
            "patient_id": self.patient_id,
            "path": self.path,
            "message": self.message,
            "context": dict(self.context),
        }


@dataclass(frozen=True)
class ValidationSummary:
    """Simple in-memory summary returned by run_all_rules()."""

    issues: tuple[ValidationIssue, ...]

    @property
    def fail_count(self) -> int:
        return sum(1 for issue in self.issues if issue.severity == FAIL)

    @property
    def warn_count(self) -> int:
        return sum(1 for issue in self.issues if issue.severity == WARN)

    @property
    def info_count(self) -> int:
        return sum(1 for issue in self.issues if issue.severity in {INFO, REPORT})

    @property
    def passed(self) -> bool:
        return self.fail_count == 0

    def as_dict(self) -> dict[str, Any]:
        return {
            "passed": self.passed,
            "fail_count": self.fail_count,
            "warn_count": self.warn_count,
            "info_count": self.info_count,
            "issues": [issue.as_dict() for issue in self.issues],
        }


# ---------------------------------------------------------------------------
# Public runner
# ---------------------------------------------------------------------------


def run_all_rules(
    patients: Sequence[PatientRecord] | PatientRecord,
    *,
    strict_diversity: bool = True,
) -> ValidationSummary:
    """Run V1-V12 validation over one patient or a dataset.

    V13 is intentionally not included here because it needs chunks after SOAP
    and chunk dry-run.  Use run_v13_similarity_report(chunks) separately.
    """

    normalized_patients = _normalize_patients(patients)

    issues: list[ValidationIssue] = []
    per_patient_rules = (
        validate_v1_chronological_visit_order,
        validate_v2_allergy_medication_contradiction,
        validate_v3_vitals_and_age_bounds,
        validate_v4_required_fields,
        validate_v5_prior_visit_integrity,
        validate_v6_duplicate_visit_ids,
        validate_v7_enums_and_ckd_rule,
        validate_v8_date_formats,
        validate_v9_bp_forbidden_in_labs_and_metadata,
        validate_v10_timeline_events_forbidden,
        validate_v11_medication_whitelist_and_trajectory,
    )

    for patient in normalized_patients:
        for rule in per_patient_rules:
            issues.extend(rule(patient))

    issues.extend(validate_v12_dataset_diversity(normalized_patients, strict=strict_diversity))
    return ValidationSummary(tuple(issues))


# Backward-compatible aliases that can be imported by validate.py/tests.
validate_patient = run_all_rules
validate_dataset = run_all_rules


# ---------------------------------------------------------------------------
# V1 - chronology
# ---------------------------------------------------------------------------


def validate_v1_chronological_visit_order(patient: PatientRecord) -> list[ValidationIssue]:
    patient_id = _patient_id(patient)
    issues: list[ValidationIssue] = []
    previous_date: date | None = None

    for index, visit in enumerate(_visits(patient)):
        path = f"visits[{index}].visit_date"
        visit_date_raw = visit.get("visit_date")
        parsed = _parse_date(visit_date_raw)
        if parsed is None:
            # V8 owns date-format failure.  Avoid duplicate noise here.
            continue
        if previous_date is not None and parsed < previous_date:
            issues.append(_issue(
                "V1",
                FAIL,
                patient_id,
                "Visit dates must be in chronological order.",
                path,
                previous_date=str(previous_date),
                current_date=str(parsed),
            ))
        previous_date = parsed

    return issues


# ---------------------------------------------------------------------------
# V2 - allergy contradiction
# ---------------------------------------------------------------------------


def validate_v2_allergy_medication_contradiction(patient: PatientRecord) -> list[ValidationIssue]:
    patient_id = _patient_id(patient)
    issues: list[ValidationIssue] = []
    allergens = {_normalize_text(item.get("allergen")) for item in _allergies(patient)}
    allergens.discard("")

    if not allergens:
        return issues

    for visit_index, visit in enumerate(_visits(patient)):
        for med_index, medication in enumerate(_medications(visit)):
            med_name = _normalize_text(medication.get("medication_name"))
            if med_name and med_name in allergens:
                issues.append(_issue(
                    "V2",
                    FAIL,
                    patient_id,
                    "Medication name must not match recorded allergy allergen.",
                    f"visits[{visit_index}].medications[{med_index}].medication_name",
                    medication_name=medication.get("medication_name"),
                    allergen=medication.get("medication_name"),
                ))

    return issues


# ---------------------------------------------------------------------------
# V3 - vitals and age bounds
# ---------------------------------------------------------------------------


def validate_v3_vitals_and_age_bounds(patient: PatientRecord) -> list[ValidationIssue]:
    patient_id = _patient_id(patient)
    issues: list[ValidationIssue] = []

    dob = _parse_date(patient.get("demographics", {}).get("date_of_birth"))
    if dob is not None:
        age = _calculate_age(dob)
        min_age, max_age = AGE_LIMITS
        if age < min_age or age > max_age:
            issues.append(_issue(
                "V3",
                FAIL,
                patient_id,
                f"Patient age must be between {min_age} and {max_age}.",
                "demographics.date_of_birth",
                age=age,
                date_of_birth=str(dob),
            ))

    for visit_index, visit in enumerate(_visits(patient)):
        vitals = visit.get("vitals", {})
        if not isinstance(vitals, Mapping):
            issues.append(_issue(
                "V3",
                FAIL,
                patient_id,
                "vitals must be an object.",
                f"visits[{visit_index}].vitals",
            ))
            continue

        for field_name, (lower, upper) in _vital_limits().items():
            value = vitals.get(field_name)
            if value is None:
                # V4 owns missing required vital fields.
                continue
            numeric = _as_float(value)
            if numeric is None or numeric < lower or numeric > upper:
                issues.append(_issue(
                    "V3",
                    FAIL,
                    patient_id,
                    f"Vital {field_name} must be numeric and between {lower} and {upper}.",
                    f"visits[{visit_index}].vitals.{field_name}",
                    value=value,
                    min=lower,
                    max=upper,
                ))

    return issues


def _vital_limits() -> dict[str, tuple[float, float]]:
    from config.constants import VITAL_LIMITS

    return dict(VITAL_LIMITS)


# ---------------------------------------------------------------------------
# V4 - schema fields and forbidden age
# ---------------------------------------------------------------------------


def validate_v4_required_fields(patient: PatientRecord) -> list[ValidationIssue]:
    patient_id = _patient_id(patient)
    issues: list[ValidationIssue] = []

    issues.extend(_require_fields(patient, REQUIRED_TOP_LEVEL_FIELDS, patient_id, "V4", ""))

    demographics = patient.get("demographics", {})
    if isinstance(demographics, Mapping):
        issues.extend(_require_fields(demographics, REQUIRED_DEMOGRAPHICS_FIELDS, patient_id, "V4", "demographics"))
        for forbidden in FORBIDDEN_DEMOGRAPHICS_FIELDS:
            if forbidden in demographics:
                issues.append(_issue(
                    "V4",
                    FAIL,
                    patient_id,
                    f"Forbidden demographics field present: {forbidden}.",
                    f"demographics.{forbidden}",
                ))
    else:
        issues.append(_issue("V4", FAIL, patient_id, "demographics must be an object.", "demographics"))

    metadata = patient.get("metadata", {})
    if isinstance(metadata, Mapping):
        issues.extend(_require_fields(
            metadata,
            REQUIRED_PATIENT_METADATA_FIELDS_V17_LITE,
            patient_id,
            "V4",
            "metadata",
        ))
    else:
        issues.append(_issue("V4", FAIL, patient_id, "metadata must be an object.", "metadata"))

    if not isinstance(patient.get("conditions"), Sequence) or isinstance(patient.get("conditions"), (str, bytes)):
        issues.append(_issue("V4", FAIL, patient_id, "conditions must be a list of condition strings.", "conditions"))

    if not isinstance(patient.get("allergy_registry"), Sequence) or isinstance(patient.get("allergy_registry"), (str, bytes)):
        issues.append(_issue("V4", FAIL, patient_id, "allergy_registry must be a list.", "allergy_registry"))

    if not isinstance(patient.get("visits"), Sequence) or isinstance(patient.get("visits"), (str, bytes)):
        issues.append(_issue("V4", FAIL, patient_id, "visits must be a list.", "visits"))
        return issues

    for allergy_index, allergy in enumerate(_allergies(patient)):
        issues.extend(_require_fields(
            allergy,
            REQUIRED_ALLERGY_FIELDS,
            patient_id,
            "V4",
            f"allergy_registry[{allergy_index}]",
        ))

    for visit_index, visit in enumerate(_visits(patient)):
        visit_path = f"visits[{visit_index}]"
        issues.extend(_require_fields(visit, REQUIRED_VISIT_FIELDS, patient_id, "V4", visit_path))

        for forbidden in FORBIDDEN_VISIT_FIELDS:
            if isinstance(visit, Mapping) and forbidden in visit:
                issues.append(_issue(
                    "V4",
                    FAIL,
                    patient_id,
                    f"Forbidden visit field present: {forbidden}.",
                    f"{visit_path}.{forbidden}",
                ))

        vitals = visit.get("vitals", {})
        if isinstance(vitals, Mapping):
            issues.extend(_require_fields(vitals, REQUIRED_VITAL_FIELDS, patient_id, "V4", f"{visit_path}.vitals"))
        else:
            issues.append(_issue("V4", FAIL, patient_id, "vitals must be an object.", f"{visit_path}.vitals"))

        soap_note = visit.get("soap_note", {})
        if isinstance(soap_note, Mapping):
            issues.extend(_require_fields(soap_note, SOAP_SECTIONS, patient_id, "V4", f"{visit_path}.soap_note"))
        else:
            issues.append(_issue("V4", FAIL, patient_id, "soap_note must be an object.", f"{visit_path}.soap_note"))

        clinical_event = visit.get("clinical_event", {})
        if isinstance(clinical_event, Mapping):
            issues.extend(_require_fields(
                clinical_event,
                REQUIRED_CLINICAL_EVENT_FIELDS,
                patient_id,
                "V4",
                f"{visit_path}.clinical_event",
            ))
        else:
            issues.append(_issue("V4", FAIL, patient_id, "clinical_event must be an object.", f"{visit_path}.clinical_event"))

        retrieval_context = visit.get("retrieval_context", {})
        if isinstance(retrieval_context, Mapping):
            issues.extend(_require_fields(
                retrieval_context,
                REQUIRED_RETRIEVAL_CONTEXT_FIELDS,
                patient_id,
                "V4",
                f"{visit_path}.retrieval_context",
            ))
        else:
            issues.append(_issue("V4", FAIL, patient_id, "retrieval_context must be an object.", f"{visit_path}.retrieval_context"))

        if not isinstance(visit.get("labs", []), Sequence) or isinstance(visit.get("labs", []), (str, bytes)):
            issues.append(_issue("V4", FAIL, patient_id, "labs must be a list.", f"{visit_path}.labs"))
        else:
            for lab_index, lab in enumerate(_labs(visit)):
                issues.extend(_require_fields(
                    lab,
                    REQUIRED_LAB_FIELDS,
                    patient_id,
                    "V4",
                    f"{visit_path}.labs[{lab_index}]",
                ))

        if not isinstance(visit.get("medications", []), Sequence) or isinstance(visit.get("medications", []), (str, bytes)):
            issues.append(_issue("V4", FAIL, patient_id, "medications must be a list.", f"{visit_path}.medications"))
        else:
            for med_index, medication in enumerate(_medications(visit)):
                issues.extend(_require_fields(
                    medication,
                    REQUIRED_MEDICATION_FIELDS,
                    patient_id,
                    "V4",
                    f"{visit_path}.medications[{med_index}]",
                ))

    return issues


# ---------------------------------------------------------------------------
# V5 - prior visit linkage
# ---------------------------------------------------------------------------


def validate_v5_prior_visit_integrity(patient: PatientRecord) -> list[ValidationIssue]:
    patient_id = _patient_id(patient)
    issues: list[ValidationIssue] = []
    visits = _visits(patient)
    known_visit_ids = {str(visit.get("visit_id")) for visit in visits if visit.get("visit_id") is not None}

    for index, visit in enumerate(visits):
        prior = visit.get("prior_visit_id")
        if index == 0:
            if prior is not None:
                issues.append(_issue(
                    "V5",
                    WARN,
                    patient_id,
                    "First visit should not have prior_visit_id.",
                    f"visits[{index}].prior_visit_id",
                    prior_visit_id=prior,
                ))
            continue

        previous_visit_id = visits[index - 1].get("visit_id")
        if prior is None:
            issues.append(_issue(
                "V5",
                WARN,
                patient_id,
                "Follow-up visit should reference the previous visit.",
                f"visits[{index}].prior_visit_id",
                expected=previous_visit_id,
            ))
        elif str(prior) not in known_visit_ids:
            issues.append(_issue(
                "V5",
                WARN,
                patient_id,
                "prior_visit_id must reference an existing visit_id.",
                f"visits[{index}].prior_visit_id",
                prior_visit_id=prior,
            ))
        elif prior != previous_visit_id:
            issues.append(_issue(
                "V5",
                WARN,
                patient_id,
                "prior_visit_id should point to the immediately previous visit for deterministic timelines.",
                f"visits[{index}].prior_visit_id",
                actual=prior,
                expected=previous_visit_id,
            ))

    return issues


# ---------------------------------------------------------------------------
# V6 - duplicate visit IDs
# ---------------------------------------------------------------------------


def validate_v6_duplicate_visit_ids(patient: PatientRecord) -> list[ValidationIssue]:
    patient_id = _patient_id(patient)
    issues: list[ValidationIssue] = []
    seen: dict[str, int] = {}

    for index, visit in enumerate(_visits(patient)):
        visit_id = str(visit.get("visit_id", ""))
        if not visit_id:
            continue
        if visit_id in seen:
            issues.append(_issue(
                "V6",
                FAIL,
                patient_id,
                "Duplicate visit_id inside patient record.",
                f"visits[{index}].visit_id",
                duplicate_visit_id=visit_id,
                first_index=seen[visit_id],
                duplicate_index=index,
            ))
        else:
            seen[visit_id] = index

    return issues


def validate_v6_duplicate_visit_ids_dataset(patients: Sequence[PatientRecord]) -> list[ValidationIssue]:
    """Optional dataset-level duplicate visit_id check."""

    issues: list[ValidationIssue] = []
    seen: dict[str, str] = {}
    for patient in patients:
        patient_id = _patient_id(patient)
        for visit in _visits(patient):
            visit_id = str(visit.get("visit_id", ""))
            if not visit_id:
                continue
            if visit_id in seen and seen[visit_id] != patient_id:
                issues.append(_issue(
                    "V6",
                    FAIL,
                    patient_id,
                    "Duplicate visit_id across dataset.",
                    "visits[].visit_id",
                    duplicate_visit_id=visit_id,
                    first_patient_id=seen[visit_id],
                    duplicate_patient_id=patient_id,
                ))
            else:
                seen[visit_id] = patient_id
    return issues


# ---------------------------------------------------------------------------
# V7 - enums and CKD rule
# ---------------------------------------------------------------------------


def validate_v7_enums_and_ckd_rule(patient: PatientRecord) -> list[ValidationIssue]:
    patient_id = _patient_id(patient)
    issues: list[ValidationIssue] = []
    metadata = patient.get("metadata", {}) if isinstance(patient.get("metadata"), Mapping) else {}
    conditions = _conditions(patient)
    tier = metadata.get("tier")

    if not _matches_regex(patient_id, PATIENT_ID_REGEX):
        issues.append(_issue("V7", FAIL, patient_id, "Invalid patient_id format.", "patient_id", value=patient_id))

    for cond_index, condition in enumerate(conditions):
        if condition not in CONDITIONS:
            issues.append(_issue(
                "V7",
                FAIL,
                patient_id,
                "Invalid condition enum value.",
                f"conditions[{cond_index}]",
                value=condition,
                allowed=CONDITIONS,
            ))

    if tier not in TIERS:
        issues.append(_issue("V7", FAIL, patient_id, "Invalid tier enum value.", "metadata.tier", value=tier, allowed=TIERS))

    sex = patient.get("demographics", {}).get("sex") if isinstance(patient.get("demographics"), Mapping) else None
    if sex not in SEX_VALUES:
        issues.append(_issue("V7", FAIL, patient_id, "Invalid sex enum value.", "demographics.sex", value=sex, allowed=SEX_VALUES))

    semantic_focus = metadata.get("semantic_focus")
    if semantic_focus not in SEMANTIC_FOCUS:
        issues.append(_issue(
            "V7",
            FAIL,
            patient_id,
            "Invalid semantic_focus enum value.",
            "metadata.semantic_focus",
            value=semantic_focus,
            allowed=SEMANTIC_FOCUS,
        ))

    timeline_pattern = metadata.get("timeline_pattern")
    if timeline_pattern not in TIMELINE_PATTERNS:
        issues.append(_issue(
            "V7",
            FAIL,
            patient_id,
            "Invalid timeline_pattern enum value.",
            "metadata.timeline_pattern",
            value=timeline_pattern,
            allowed=TIMELINE_PATTERNS,
        ))

    soap_style = metadata.get("soap_style")
    if soap_style not in SOAP_STYLES:
        issues.append(_issue("V7", FAIL, patient_id, "Invalid soap_style enum value.", "metadata.soap_style", value=soap_style, allowed=SOAP_STYLES))

    for tag_index, tag in enumerate(_as_list(metadata.get("retrieval_intent_tags"))):
        if tag not in RETRIEVAL_INTENT_TAGS:
            issues.append(_issue(
                "V7",
                FAIL,
                patient_id,
                "Invalid retrieval_intent_tag value.",
                f"metadata.retrieval_intent_tags[{tag_index}]",
                value=tag,
                allowed=RETRIEVAL_INTENT_TAGS,
            ))

    for target_index, target in enumerate(_as_list(metadata.get("primary_retrieval_targets"))):
        if target not in PRIMARY_RETRIEVAL_TARGETS:
            issues.append(_issue(
                "V7",
                FAIL,
                patient_id,
                "Invalid primary_retrieval_target value.",
                f"metadata.primary_retrieval_targets[{target_index}]",
                value=target,
                allowed=PRIMARY_RETRIEVAL_TARGETS,
            ))

    if "CKD" in conditions:
        missing_required = [condition for condition in CKD_REQUIRED_CONDITIONS if condition not in conditions]
        if missing_required or tier != CKD_ALLOWED_TIER:
            issues.append(_issue(
                "V7",
                FAIL,
                patient_id,
                "CKD requires chronic tier and co-occurring T2DM + HTN.",
                "conditions",
                conditions=conditions,
                tier=tier,
                missing_required_conditions=missing_required,
            ))

    for visit_index, visit in enumerate(_visits(patient)):
        visit_path = f"visits[{visit_index}]"
        visit_id = str(visit.get("visit_id", ""))
        if visit_id and not _matches_regex(visit_id, VISIT_ID_REGEX):
            issues.append(_issue("V7", FAIL, patient_id, "Invalid visit_id format.", f"{visit_path}.visit_id", value=visit_id))

        visit_type = visit.get("visit_type")
        if visit_type not in VISIT_TYPES:
            issues.append(_issue("V7", FAIL, patient_id, "Invalid visit_type enum value.", f"{visit_path}.visit_type", value=visit_type, allowed=VISIT_TYPES))

        visit_role = visit.get("visit_role")
        if visit_role not in VISIT_ROLES:
            issues.append(_issue("V7", FAIL, patient_id, "Invalid visit_role enum value.", f"{visit_path}.visit_role", value=visit_role, allowed=VISIT_ROLES))

        visit_timeline = visit.get("timeline_pattern")
        if visit_timeline not in TIMELINE_PATTERNS:
            issues.append(_issue("V7", FAIL, patient_id, "Invalid visit timeline_pattern.", f"{visit_path}.timeline_pattern", value=visit_timeline, allowed=TIMELINE_PATTERNS))
        elif timeline_pattern in TIMELINE_PATTERNS and visit_timeline != timeline_pattern:
            issues.append(_issue(
                "V7",
                FAIL,
                patient_id,
                "Visit timeline_pattern must match patient metadata timeline_pattern.",
                f"{visit_path}.timeline_pattern",
                visit_value=visit_timeline,
                patient_value=timeline_pattern,
            ))

        for diag_index, diagnosis in enumerate(_as_list(visit.get("diagnoses"))):
            if diagnosis not in CONDITIONS:
                issues.append(_issue("V7", FAIL, patient_id, "Invalid diagnosis enum value.", f"{visit_path}.diagnoses[{diag_index}]", value=diagnosis, allowed=CONDITIONS))
            elif diagnosis not in conditions:
                issues.append(_issue(
                    "V7",
                    FAIL,
                    patient_id,
                    "Visit diagnosis must be present in patient.conditions.",
                    f"{visit_path}.diagnoses[{diag_index}]",
                    diagnosis=diagnosis,
                    patient_conditions=conditions,
                ))

        clinical_event = visit.get("clinical_event", {}) if isinstance(visit.get("clinical_event"), Mapping) else {}
        event_type = clinical_event.get("event_type")
        if event_type not in CLINICAL_EVENT_TYPES:
            issues.append(_issue("V7", FAIL, patient_id, "Invalid clinical_event.event_type.", f"{visit_path}.clinical_event.event_type", value=event_type, allowed=CLINICAL_EVENT_TYPES))

        retrieval_context = visit.get("retrieval_context", {}) if isinstance(visit.get("retrieval_context"), Mapping) else {}
        if retrieval_context.get("semantic_focus") not in SEMANTIC_FOCUS:
            issues.append(_issue("V7", FAIL, patient_id, "Invalid retrieval_context.semantic_focus.", f"{visit_path}.retrieval_context.semantic_focus", value=retrieval_context.get("semantic_focus"), allowed=SEMANTIC_FOCUS))

        for tag_index, tag in enumerate(_as_list(retrieval_context.get("retrieval_intent_tags"))):
            if tag not in RETRIEVAL_INTENT_TAGS:
                issues.append(_issue("V7", FAIL, patient_id, "Invalid retrieval_context tag.", f"{visit_path}.retrieval_context.retrieval_intent_tags[{tag_index}]", value=tag, allowed=RETRIEVAL_INTENT_TAGS))

        for lab_index, lab in enumerate(_labs(visit)):
            lab_type = lab.get("lab_type")
            if lab_type not in LAB_TYPES:
                issues.append(_issue("V7", FAIL, patient_id, "Invalid lab_type enum value.", f"{visit_path}.labs[{lab_index}].lab_type", value=lab_type, allowed=LAB_TYPES))
            flag = lab.get("flag")
            if flag not in FLAGS:
                issues.append(_issue("V7", FAIL, patient_id, "Invalid lab flag enum value.", f"{visit_path}.labs[{lab_index}].flag", value=flag, allowed=FLAGS))

        for med_index, medication in enumerate(_medications(visit)):
            frequency = medication.get("frequency")
            route = medication.get("route")
            medication_status = medication.get("medication_status")
            trajectory_event = medication.get("trajectory_event")
            if frequency not in FREQUENCIES:
                issues.append(_issue("V7", FAIL, patient_id, "Invalid medication frequency enum value.", f"{visit_path}.medications[{med_index}].frequency", value=frequency, allowed=FREQUENCIES))
            if route not in ROUTES:
                issues.append(_issue("V7", FAIL, patient_id, "Invalid medication route enum value.", f"{visit_path}.medications[{med_index}].route", value=route, allowed=ROUTES))
            if medication_status not in MEDICATION_STATUS:
                issues.append(_issue("V7", FAIL, patient_id, "Invalid medication_status enum value.", f"{visit_path}.medications[{med_index}].medication_status", value=medication_status, allowed=MEDICATION_STATUS))
            if trajectory_event not in MEDICATION_TRAJECTORY_EVENTS:
                issues.append(_issue("V7", FAIL, patient_id, "Invalid trajectory_event enum value.", f"{visit_path}.medications[{med_index}].trajectory_event", value=trajectory_event, allowed=MEDICATION_TRAJECTORY_EVENTS))

    for allergy_index, allergy in enumerate(_allergies(patient)):
        severity = allergy.get("severity")
        if severity not in SEVERITIES:
            issues.append(_issue("V7", FAIL, patient_id, "Invalid allergy severity enum value.", f"allergy_registry[{allergy_index}].severity", value=severity, allowed=SEVERITIES))

    return issues


# ---------------------------------------------------------------------------
# V8 - date formats
# ---------------------------------------------------------------------------


def validate_v8_date_formats(patient: PatientRecord) -> list[ValidationIssue]:
    patient_id = _patient_id(patient)
    issues: list[ValidationIssue] = []

    date_fields: list[tuple[str, Any]] = []
    demographics = patient.get("demographics", {}) if isinstance(patient.get("demographics"), Mapping) else {}
    date_fields.append(("demographics.date_of_birth", demographics.get("date_of_birth")))

    for allergy_index, allergy in enumerate(_allergies(patient)):
        date_fields.append((f"allergy_registry[{allergy_index}].recorded_date", allergy.get("recorded_date")))

    for visit_index, visit in enumerate(_visits(patient)):
        date_fields.append((f"visits[{visit_index}].visit_date", visit.get("visit_date")))
        for med_index, medication in enumerate(_medications(visit)):
            date_fields.append((f"visits[{visit_index}].medications[{med_index}].start_date", medication.get("start_date")))
            stop_date = medication.get("stop_date")
            if stop_date is not None:
                date_fields.append((f"visits[{visit_index}].medications[{med_index}].stop_date", stop_date))

    for path, value in date_fields:
        if not isinstance(value, str) or not _matches_regex(value, DATE_REGEX) or _parse_date(value) is None:
            issues.append(_issue(
                "V8",
                FAIL,
                patient_id,
                f"Date must use {DATE_FORMAT} / YYYY-MM-DD format.",
                path,
                value=value,
            ))

    return issues


# ---------------------------------------------------------------------------
# V9 - BP forbidden in labs and metadata
# ---------------------------------------------------------------------------


def validate_v9_bp_forbidden_in_labs_and_metadata(patient: PatientRecord) -> list[ValidationIssue]:
    patient_id = _patient_id(patient)
    issues: list[ValidationIssue] = []

    for visit_index, visit in enumerate(_visits(patient)):
        for lab_index, lab in enumerate(_labs(visit)):
            lab_type = _normalize_text(lab.get("lab_type"))
            if _contains_forbidden_term(lab_type, BP_FORBIDDEN_LAB_TERMS):
                issues.append(_issue(
                    "V9",
                    FAIL,
                    patient_id,
                    "Blood pressure must not be stored in labs.",
                    f"visits[{visit_index}].labs[{lab_index}].lab_type",
                    lab_type=lab.get("lab_type"),
                ))

    metadata = patient.get("metadata", {}) if isinstance(patient.get("metadata"), Mapping) else {}
    issues.extend(validate_metadata_bp_absence(metadata, patient_id=patient_id, base_path="metadata", check_values=False))

    return issues


def validate_metadata_bp_absence(
    metadata: Mapping[str, Any],
    *,
    patient_id: str = "UNKNOWN",
    base_path: str = "metadata",
    check_values: bool = False,
) -> list[ValidationIssue]:
    """Check any metadata-like dict for forbidden BP terms.

    This is useful for ingestion/metadata_builder tests without importing or
    calling ChromaDB.  It checks keys and simple scalar values recursively.
    """

    issues: list[ValidationIssue] = []
    for path, key, value in _walk_mapping(metadata, base_path=base_path):
        normalized_key = _normalize_text(key)
        if _contains_forbidden_term(normalized_key, BP_FORBIDDEN_METADATA_TERMS):
            issues.append(_issue(
                "V9",
                FAIL,
                patient_id,
                "Blood pressure fields are forbidden in metadata.",
                path,
                key=key,
            ))
        if check_values and isinstance(value, str) and _contains_forbidden_term(_normalize_text(value), BP_FORBIDDEN_METADATA_TERMS):
            issues.append(_issue(
                "V9",
                FAIL,
                patient_id,
                "Blood pressure text is forbidden in metadata values.",
                path,
                value=value,
            ))
    return issues


# ---------------------------------------------------------------------------
# V10 - timeline_events forbidden
# ---------------------------------------------------------------------------


def validate_v10_timeline_events_forbidden(patient: PatientRecord) -> list[ValidationIssue]:
    patient_id = _patient_id(patient)
    issues: list[ValidationIssue] = []

    for path, _value in _find_key_recursively(patient, "timeline_events"):
        issues.append(_issue(
            "V10",
            FAIL,
            patient_id,
            "timeline_events is forbidden in patient JSON.",
            path,
        ))

    return issues


# ---------------------------------------------------------------------------
# V11 - medication whitelist and trajectory rules
# ---------------------------------------------------------------------------


def validate_v11_medication_whitelist_and_trajectory(patient: PatientRecord) -> list[ValidationIssue]:
    patient_id = _patient_id(patient)
    issues: list[ValidationIssue] = []
    conditions = set(_conditions(patient))
    seen_by_medication: dict[str, list[tuple[int, str, str]]] = {}

    for visit_index, visit in enumerate(_visits(patient)):
        visit_role = str(visit.get("visit_role", ""))
        visit_type = str(visit.get("visit_type", ""))
        event_type = ""
        if isinstance(visit.get("clinical_event"), Mapping):
            event_type = str(visit.get("clinical_event", {}).get("event_type", ""))

        for med_index, medication in enumerate(_medications(visit)):
            med_path = f"visits[{visit_index}].medications[{med_index}]"
            name = medication.get("medication_name")
            status = medication.get("medication_status")
            trajectory = medication.get("trajectory_event")
            frequency = medication.get("frequency")
            route = medication.get("route")

            if name not in MEDICATION_NAMES:
                issues.append(_issue(
                    "V11",
                    FAIL,
                    patient_id,
                    "Medication must be in MEDICATION_WHITELIST.",
                    f"{med_path}.medication_name",
                    value=name,
                    allowed=MEDICATION_NAMES,
                ))
                continue

            whitelist_entry = MEDICATION_WHITELIST[str(name)]

            expected_class = whitelist_entry.get("medication_class")
            if medication.get("medication_class") != expected_class:
                issues.append(_issue(
                    "V11",
                    FAIL,
                    patient_id,
                    "Medication class must match MEDICATION_WHITELIST.",
                    f"{med_path}.medication_class",
                    medication_name=name,
                    value=medication.get("medication_class"),
                    expected=expected_class,
                ))

            expected_frequency = whitelist_entry.get("frequency")
            if frequency not in FREQUENCIES or frequency != expected_frequency:
                issues.append(_issue(
                    "V11",
                    FAIL,
                    patient_id,
                    "Medication frequency must be allowed and match whitelist default.",
                    f"{med_path}.frequency",
                    medication_name=name,
                    value=frequency,
                    expected=expected_frequency,
                ))

            expected_route = whitelist_entry.get("route")
            if route not in ROUTES or route != expected_route:
                issues.append(_issue(
                    "V11",
                    FAIL,
                    patient_id,
                    "Medication route must be allowed and match whitelist default.",
                    f"{med_path}.route",
                    medication_name=name,
                    value=route,
                    expected=expected_route,
                ))

            med_condition = whitelist_entry.get("condition")
            if med_condition and med_condition not in conditions:
                issues.append(_issue(
                    "V11",
                    FAIL,
                    patient_id,
                    "Medication condition must be present in patient.conditions.",
                    f"{med_path}.medication_name",
                    medication_name=name,
                    medication_condition=med_condition,
                    patient_conditions=sorted(conditions),
                ))

            if status not in MEDICATION_STATUS:
                issues.append(_issue("V11", FAIL, patient_id, "Invalid medication_status.", f"{med_path}.medication_status", value=status, allowed=MEDICATION_STATUS))

            if trajectory not in MEDICATION_TRAJECTORY_EVENTS:
                issues.append(_issue("V11", FAIL, patient_id, "Invalid trajectory_event.", f"{med_path}.trajectory_event", value=trajectory, allowed=MEDICATION_TRAJECTORY_EVENTS))

            # adherence_interruption is valid only for the condition-specific
            # adherence-target medication.  In the v1.7 Lite dataset:
            #   - T2DM patients → only Metformin may carry adherence_interruption
            #   - IDA  patients → only Ferrous sulfate may carry adherence_interruption
            # Other initial medications (e.g. Amlodipine for HTN in PAT-CHR-001)
            # must use simple_start_continue at adherence visits.
            if trajectory == "adherence_interruption" and not _is_adherence_target(
                medication_name=str(name), conditions=conditions
            ):
                issues.append(_issue(
                    "V11",
                    FAIL,
                    patient_id,
                    "adherence_interruption is only valid for the condition-specific "
                    "adherence target (Metformin for T2DM, Ferrous sulfate for IDA).",
                    f"{med_path}.trajectory_event",
                    medication_name=name,
                    patient_conditions=sorted(conditions),
                ))

            if status == "completed" and name not in SHORT_COURSE_MEDICATIONS:
                issues.append(_issue(
                    "V11",
                    FAIL,
                    patient_id,
                    "completed status is reserved for short-course medications.",
                    f"{med_path}.medication_status",
                    medication_name=name,
                    short_course_medications=SHORT_COURSE_MEDICATIONS,
                ))

            if trajectory == "course_completed" and name not in SHORT_COURSE_MEDICATIONS:
                issues.append(_issue(
                    "V11",
                    FAIL,
                    patient_id,
                    "course_completed trajectory is reserved for short-course medications.",
                    f"{med_path}.trajectory_event",
                    medication_name=name,
                ))

            if trajectory == "dose_adjustment" and status not in {"dose_adjusted", "added"}:
                issues.append(_issue(
                    "V11",
                    FAIL,
                    patient_id,
                    "dose_adjustment trajectory should use dose_adjusted status, or added when a controller medication is newly introduced.",
                    f"{med_path}.trajectory_event",
                    status=status,
                    trajectory_event=trajectory,
                ))

            if trajectory == "second_medication_added" and status != "added":
                issues.append(_issue(
                    "V11",
                    FAIL,
                    patient_id,
                    "second_medication_added trajectory should use added status.",
                    f"{med_path}.trajectory_event",
                    status=status,
                    trajectory_event=trajectory,
                ))

            if trajectory == "post_discharge_reconciliation" and not _has_post_discharge_context(visit_role, visit_type, event_type):
                issues.append(_issue(
                    "V11",
                    FAIL,
                    patient_id,
                    "post_discharge_reconciliation requires hospitalization or post-discharge context.",
                    f"{med_path}.trajectory_event",
                    visit_role=visit_role,
                    visit_type=visit_type,
                    event_type=event_type,
                ))

            start_date = _parse_date(medication.get("start_date"))
            stop_date = _parse_date(medication.get("stop_date")) if medication.get("stop_date") is not None else None
            if start_date is not None and stop_date is not None and stop_date < start_date:
                issues.append(_issue(
                    "V11",
                    FAIL,
                    patient_id,
                    "Medication stop_date must not be earlier than start_date.",
                    f"{med_path}.stop_date",
                    start_date=medication.get("start_date"),
                    stop_date=medication.get("stop_date"),
                ))

            seen_by_medication.setdefault(str(name), []).append((visit_index, str(status), str(trajectory)))

    for medication_name, entries in seen_by_medication.items():
        prior_statuses: set[str] = set()
        was_active = False
        for visit_index, status, trajectory in entries:
            if status == "restarted" and "temporarily_stopped" not in prior_statuses:
                issues.append(_issue(
                    "V11",
                    FAIL,
                    patient_id,
                    "restarted requires a prior temporarily_stopped event.",
                    f"visits[{visit_index}].medications[].medication_status",
                    medication_name=medication_name,
                ))
            if status == "added" and was_active:
                issues.append(_issue(
                    "V11",
                    FAIL,
                    patient_id,
                    "added should be used only before the medication was previously active.",
                    f"visits[{visit_index}].medications[].medication_status",
                    medication_name=medication_name,
                ))
            prior_statuses.add(status)
            if status in {"started", "continued", "dose_adjusted", "restarted", "added"}:
                was_active = True
            if status in {"temporarily_stopped", "completed", "stopped"}:
                was_active = False

    return issues


# ---------------------------------------------------------------------------
# V12 - dataset diversity
# ---------------------------------------------------------------------------


def validate_v12_dataset_diversity(
    patients: Sequence[PatientRecord] | PatientRecord,
    *,
    strict: bool = True,
) -> list[ValidationIssue]:
    """Validate v1.7 Lite retrieval diversity across the dataset.

    During active development, callers may set strict=False to downgrade
    duplicate-fingerprint findings to WARN.  Before final ingestion, keep
    strict=True so diversity issues block the pipeline.
    """

    normalized_patients = _normalize_patients(patients)
    severity = FAIL if strict else WARN
    issues: list[ValidationIssue] = []
    signatures: dict[str, str] = {}
    fingerprints: dict[tuple[Any, ...], str] = {}
    condition_focus_timeline: dict[tuple[str, str, str], str] = {}

    issues.extend(validate_v6_duplicate_visit_ids_dataset(normalized_patients))

    for patient in normalized_patients:
        patient_id = _patient_id(patient)
        metadata = patient.get("metadata", {}) if isinstance(patient.get("metadata"), Mapping) else {}
        conditions = _conditions(patient)
        semantic_focus = metadata.get("semantic_focus")
        timeline_pattern = metadata.get("timeline_pattern")
        retrieval_signature = metadata.get("retrieval_signature")
        retrieval_intent_tags = _as_list(metadata.get("retrieval_intent_tags"))

        if not retrieval_signature:
            issues.append(_issue("V12", severity, patient_id, "Patient must have retrieval_signature.", "metadata.retrieval_signature"))
        elif retrieval_signature in signatures:
            issues.append(_issue(
                "V12",
                severity,
                patient_id,
                "Duplicate retrieval_signature across patients.",
                "metadata.retrieval_signature",
                retrieval_signature=retrieval_signature,
                first_patient_id=signatures[str(retrieval_signature)],
            ))
        else:
            signatures[str(retrieval_signature)] = patient_id

        if len(retrieval_intent_tags) < MIN_RETRIEVAL_INTENT_TAGS or len(retrieval_intent_tags) > MAX_RETRIEVAL_INTENT_TAGS:
            issues.append(_issue(
                "V12",
                severity,
                patient_id,
                f"Each patient must have {MIN_RETRIEVAL_INTENT_TAGS}-{MAX_RETRIEVAL_INTENT_TAGS} retrieval_intent_tags.",
                "metadata.retrieval_intent_tags",
                count=len(retrieval_intent_tags),
                tags=retrieval_intent_tags,
            ))

        for tag_index, tag in enumerate(retrieval_intent_tags):
            if tag not in RETRIEVAL_INTENT_TAGS:
                issues.append(_issue(
                    "V12",
                    severity,
                    patient_id,
                    "retrieval_intent_tag must be from controlled list.",
                    f"metadata.retrieval_intent_tags[{tag_index}]",
                    tag=tag,
                ))

        for visit_index, visit in enumerate(_visits(patient)):
            if not visit.get("visit_role"):
                issues.append(_issue("V12", severity, patient_id, "Every visit must have visit_role.", f"visits[{visit_index}].visit_role"))
            if not isinstance(visit.get("clinical_event"), Mapping) or not visit.get("clinical_event"):
                issues.append(_issue("V12", severity, patient_id, "Every visit must have clinical_event.", f"visits[{visit_index}].clinical_event"))
            if not isinstance(visit.get("retrieval_context"), Mapping) or not visit.get("retrieval_context"):
                issues.append(_issue("V12", severity, patient_id, "Every visit must have retrieval_context.", f"visits[{visit_index}].retrieval_context"))

        fingerprint = build_diversity_fingerprint(patient)
        if fingerprint in fingerprints:
            issues.append(_issue(
                "V12",
                severity,
                patient_id,
                "Duplicate diversity fingerprint across patients.",
                "metadata",
                first_patient_id=fingerprints[fingerprint],
                fingerprint=repr(fingerprint),
            ))
        else:
            fingerprints[fingerprint] = patient_id

        for condition in conditions:
            key = (condition, str(semantic_focus), str(timeline_pattern))
            if key in condition_focus_timeline and condition_focus_timeline[key] != patient_id:
                issues.append(_issue(
                    "V12",
                    severity,
                    patient_id,
                    "Patients with overlapping primary conditions should not share both semantic_focus and timeline_pattern.",
                    "metadata.semantic_focus",
                    condition=condition,
                    semantic_focus=semantic_focus,
                    timeline_pattern=timeline_pattern,
                    first_patient_id=condition_focus_timeline[key],
                ))
            else:
                condition_focus_timeline[key] = patient_id

    return issues


def build_diversity_fingerprint(patient: PatientRecord) -> tuple[Any, ...]:
    """Build the v1.7 Lite diversity fingerprint for one patient."""

    metadata = patient.get("metadata", {}) if isinstance(patient.get("metadata"), Mapping) else {}
    visit_roles = tuple(str(visit.get("visit_role", "")) for visit in _visits(patient))
    main_medications = tuple(sorted({
        str(medication.get("medication_name"))
        for visit in _visits(patient)
        for medication in _medications(visit)
        if medication.get("medication_name")
    }))
    lab_focus = tuple(sorted({
        str(lab.get("lab_type"))
        for visit in _visits(patient)
        for lab in _labs(visit)
        if lab.get("lab_type")
    }))
    allergy_allergen = tuple(sorted({
        str(allergy.get("allergen"))
        for allergy in _allergies(patient)
        if allergy.get("allergen")
    }))

    return (
        metadata.get("tier"),
        tuple(sorted(_conditions(patient))),
        metadata.get("semantic_focus"),
        metadata.get("timeline_pattern"),
        visit_roles,
        main_medications,
        lab_focus,
        allergy_allergen,
    )


# ---------------------------------------------------------------------------
# Metadata contract helper for Gamal / ingestion tests
# ---------------------------------------------------------------------------


def validate_chroma_metadata_contract(
    metadata: Mapping[str, Any],
    *,
    patient_id: str = "UNKNOWN",
    source_type_required: bool = True,
) -> list[ValidationIssue]:
    """Validate minimal ChromaDB metadata without calling ChromaDB.

    This helper is intentionally placed here so tests can reuse the same safety
    rules while metadata_builder.py still owns actual metadata construction.
    """

    issues: list[ValidationIssue] = []
    allowed_fields = set(MINIMAL_CHROMA_METADATA_FIELDS_V17_LITE) | set(OPTIONAL_CHROMA_METADATA_FIELDS_V17_LITE)

    for required in MINIMAL_CHROMA_METADATA_FIELDS_V17_LITE:
        if required not in metadata:
            if required == "source_type" and not source_type_required:
                continue
            issues.append(_issue(
                "METADATA",
                FAIL,
                patient_id,
                "Required Chroma metadata field missing.",
                f"metadata.{required}",
                field=required,
            ))

    for key in metadata.keys():
        if key in FORBIDDEN_CHROMA_METADATA_FIELDS_V17_LITE:
            issues.append(_issue(
                "METADATA",
                FAIL,
                patient_id,
                "Forbidden Chroma metadata field present.",
                f"metadata.{key}",
                field=key,
            ))
        if key not in allowed_fields:
            issues.append(_issue(
                "METADATA",
                WARN,
                patient_id,
                "Metadata field is outside the v1.7 Lite minimal contract.",
                f"metadata.{key}",
                field=key,
            ))

    if metadata.get("source_type") is not None and metadata.get("source_type") not in SOURCE_TYPES:
        issues.append(_issue(
            "METADATA",
            FAIL,
            patient_id,
            "Invalid source_type in Chroma metadata.",
            "metadata.source_type",
            value=metadata.get("source_type"),
            allowed=SOURCE_TYPES,
        ))

    if metadata.get("visit_type") is not None and metadata.get("visit_type") not in VISIT_TYPES:
        issues.append(_issue("METADATA", FAIL, patient_id, "Invalid visit_type in metadata.", "metadata.visit_type", value=metadata.get("visit_type"), allowed=VISIT_TYPES))
    if metadata.get("visit_role") is not None and metadata.get("visit_role") not in VISIT_ROLES:
        issues.append(_issue("METADATA", FAIL, patient_id, "Invalid visit_role in metadata.", "metadata.visit_role", value=metadata.get("visit_role"), allowed=VISIT_ROLES))
    if metadata.get("semantic_focus") is not None and metadata.get("semantic_focus") not in SEMANTIC_FOCUS:
        issues.append(_issue("METADATA", FAIL, patient_id, "Invalid semantic_focus in metadata.", "metadata.semantic_focus", value=metadata.get("semantic_focus"), allowed=SEMANTIC_FOCUS))
    if metadata.get("timeline_pattern") is not None and metadata.get("timeline_pattern") not in TIMELINE_PATTERNS:
        issues.append(_issue("METADATA", FAIL, patient_id, "Invalid timeline_pattern in metadata.", "metadata.timeline_pattern", value=metadata.get("timeline_pattern"), allowed=TIMELINE_PATTERNS))

    issues.extend(validate_metadata_bp_absence(metadata, patient_id=patient_id, base_path="metadata", check_values=False))
    return issues


# ---------------------------------------------------------------------------
# V13 - report-only embedding similarity helper
# ---------------------------------------------------------------------------


def run_v13_similarity_report(
    chunks: Sequence[Mapping[str, Any]],
    *,
    model_name: str = EMBEDDING_MODEL_NAME,
    warn_threshold: float = V13_SIMILARITY_WARN_THRESHOLD,
    critical_threshold: float = V13_SIMILARITY_CRITICAL_THRESHOLD,
    source_types_to_check: set[str] | None = None,
) -> dict[str, Any]:
    """Run report-only chunk similarity audit.

    This function is intentionally optional and lazy-imports sentence_transformers.
    It should be called after SOAP generation and chunk dry-run, not during
    patient JSON validation.  It does not call ChromaDB.
    """

    if source_types_to_check is None:
        source_types_to_check = {"doctor_note", "discharge_summary", "medication_reconciliation"}

    auditable = [
        chunk
        for chunk in chunks
        if isinstance(chunk.get("metadata"), Mapping)
        and chunk.get("metadata", {}).get("source_type") in source_types_to_check
        and str(chunk.get("text", "")).strip()
    ]

    report: dict[str, Any] = {
        "rule_id": "V13",
        "status": "report_only",
        "model": model_name,
        "chunks_checked": len(auditable),
        "critical": [],
        "warnings": [],
        "informational": [],
    }

    if len(auditable) < 2:
        return report

    texts = [str(chunk["text"]) for chunk in auditable]

    try:
        from sentence_transformers import SentenceTransformer  # type: ignore
    except Exception as exc:  # pragma: no cover - environment dependent
        report["status"] = "skipped_missing_dependency"
        report["message"] = "sentence-transformers is not installed; V13 was skipped."
        report["error"] = str(exc)
        return report

    model = SentenceTransformer(model_name)
    embeddings = model.encode(texts, normalize_embeddings=True)

    for i, j in combinations(range(len(auditable)), 2):
        chunk_a = auditable[i]
        chunk_b = auditable[j]
        metadata_a = chunk_a.get("metadata", {})
        metadata_b = chunk_b.get("metadata", {})

        if metadata_a.get("visit_id") == metadata_b.get("visit_id"):
            continue

        similarity = float(embeddings[i] @ embeddings[j])
        same_patient = metadata_a.get("patient_id") == metadata_b.get("patient_id")
        same_source = metadata_a.get("source_type") == metadata_b.get("source_type")

        record = {
            "similarity": round(similarity, 4),
            "chunk_a": chunk_a.get("chunk_id"),
            "chunk_b": chunk_b.get("chunk_id"),
            "patient_a": metadata_a.get("patient_id"),
            "patient_b": metadata_b.get("patient_id"),
            "source_type_a": metadata_a.get("source_type"),
            "source_type_b": metadata_b.get("source_type"),
            "same_patient": same_patient,
            "same_source": same_source,
        }

        if not same_patient and same_source and similarity >= critical_threshold:
            report["critical"].append(record)
        elif same_source and similarity >= warn_threshold:
            report["warnings"].append(record)
        elif same_source and similarity >= 0.82:
            report["informational"].append(record)

    return report


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _normalize_patients(patients: Sequence[PatientRecord] | PatientRecord) -> list[PatientRecord]:
    if isinstance(patients, Mapping):
        return [dict(patients)]
    return [dict(patient) for patient in patients]


def _patient_id(patient: Mapping[str, Any]) -> str:
    return str(patient.get("patient_id", "UNKNOWN"))


def _conditions(patient: Mapping[str, Any]) -> list[str]:
    return [str(value) for value in _as_list(patient.get("conditions"))]


def _visits(patient: Mapping[str, Any]) -> list[VisitRecord]:
    visits = patient.get("visits", [])
    if not isinstance(visits, Sequence) or isinstance(visits, (str, bytes)):
        return []
    return [dict(visit) for visit in visits if isinstance(visit, Mapping)]


def _labs(visit: Mapping[str, Any]) -> list[dict[str, Any]]:
    labs = visit.get("labs", [])
    if not isinstance(labs, Sequence) or isinstance(labs, (str, bytes)):
        return []
    return [dict(lab) for lab in labs if isinstance(lab, Mapping)]


def _medications(visit: Mapping[str, Any]) -> list[dict[str, Any]]:
    medications = visit.get("medications", [])
    if not isinstance(medications, Sequence) or isinstance(medications, (str, bytes)):
        return []
    return [dict(medication) for medication in medications if isinstance(medication, Mapping)]


def _allergies(patient: Mapping[str, Any]) -> list[dict[str, Any]]:
    allergies = patient.get("allergy_registry", [])
    if not isinstance(allergies, Sequence) or isinstance(allergies, (str, bytes)):
        return []
    return [dict(allergy) for allergy in allergies if isinstance(allergy, Mapping)]


def _as_list(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, (str, bytes)):
        return [value]
    if isinstance(value, Sequence):
        return list(value)
    return [value]


def _require_fields(
    obj: Mapping[str, Any],
    required_fields: Iterable[str],
    patient_id: str,
    rule_id: str,
    base_path: str,
) -> list[ValidationIssue]:
    issues: list[ValidationIssue] = []
    for field_name in required_fields:
        if field_name not in obj:
            path = f"{base_path}.{field_name}" if base_path else field_name
            issues.append(_issue(
                rule_id,
                FAIL,
                patient_id,
                f"Required field missing: {field_name}.",
                path,
                field=field_name,
            ))
    return issues


def _issue(
    rule_id: str,
    severity: ValidationSeverity,
    patient_id: str,
    message: str,
    path: str = "",
    **context: Any,
) -> ValidationIssue:
    return ValidationIssue(
        rule_id=rule_id,
        severity=severity,
        patient_id=patient_id,
        message=message,
        path=path,
        context=context,
    )


def _parse_date(value: Any) -> date | None:
    if not isinstance(value, str):
        return None
    if not _matches_regex(value, DATE_REGEX):
        return None
    try:
        return datetime.strptime(value, DATE_FORMAT).date()
    except ValueError:
        return None


def _calculate_age(dob: date, *, reference_date: date | None = None) -> int:
    ref = reference_date or date.today()
    return ref.year - dob.year - ((ref.month, ref.day) < (dob.month, dob.day))


def _matches_regex(value: str, pattern: str) -> bool:
    return re.match(pattern, str(value)) is not None


def _normalize_text(value: Any) -> str:
    return str(value or "").strip().casefold()


def _as_float(value: Any) -> float | None:
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return None
    if math.isnan(numeric) or math.isinf(numeric):
        return None
    return numeric


def _contains_forbidden_term(text: str, forbidden_terms: Iterable[str]) -> bool:
    normalized = _normalize_text(text)
    return any(_normalize_text(term) in normalized for term in forbidden_terms)


def _has_post_discharge_context(visit_role: str, visit_type: str, event_type: str) -> bool:
    values = {visit_role, visit_type, event_type}
    return bool(
        values
        & {
            "hospitalization",
            "post_discharge_stabilization",
            "post_discharge_review",
            "medication_reconciliation",
        }
    )


def _is_adherence_target(medication_name: str, conditions: set[str]) -> bool:
    """Return True when medication_name is the documented adherence target
    for this patient's conditions.

    adherence_interruption must not be applied broadly to every initial
    medication at an adherence visit — only the condition-specific adherence
    target should carry this trajectory.  For the v1.7 Lite dataset:
      - T2DM → Metformin (missed diabetes medication doses)
      - IDA  → Ferrous sulfate (missed iron supplement doses)
    All other medications at adherence visits must use simple_start_continue.
    """
    if "T2DM" in conditions and medication_name == "Metformin":
        return True
    if "IDA" in conditions and medication_name == "Ferrous sulfate":
        return True
    return False


def _walk_mapping(mapping: Mapping[str, Any], *, base_path: str) -> Iterable[tuple[str, str, Any]]:
    for key, value in mapping.items():
        path = f"{base_path}.{key}" if base_path else str(key)
        yield path, str(key), value
        if isinstance(value, Mapping):
            yield from _walk_mapping(value, base_path=path)
        elif isinstance(value, Sequence) and not isinstance(value, (str, bytes)):
            for index, item in enumerate(value):
                item_path = f"{path}[{index}]"
                if isinstance(item, Mapping):
                    yield from _walk_mapping(item, base_path=item_path)
                else:
                    yield item_path, str(key), item


def _find_key_recursively(value: Any, key_to_find: str, *, path: str = "") -> Iterable[tuple[str, Any]]:
    if isinstance(value, Mapping):
        for key, child in value.items():
            child_path = f"{path}.{key}" if path else str(key)
            if key == key_to_find:
                yield child_path, child
            yield from _find_key_recursively(child, key_to_find, path=child_path)
    elif isinstance(value, Sequence) and not isinstance(value, (str, bytes)):
        for index, child in enumerate(value):
            child_path = f"{path}[{index}]" if path else f"[{index}]"
            yield from _find_key_recursively(child, key_to_find, path=child_path)


__all__ = [
    "FAIL",
    "WARN",
    "INFO",
    "REPORT",
    "ValidationIssue",
    "ValidationSummary",
    "run_all_rules",
    "validate_patient",
    "validate_dataset",
    "validate_v1_chronological_visit_order",
    "validate_v2_allergy_medication_contradiction",
    "validate_v3_vitals_and_age_bounds",
    "validate_v4_required_fields",
    "validate_v5_prior_visit_integrity",
    "validate_v6_duplicate_visit_ids",
    "validate_v6_duplicate_visit_ids_dataset",
    "validate_v7_enums_and_ckd_rule",
    "validate_v8_date_formats",
    "validate_v9_bp_forbidden_in_labs_and_metadata",
    "validate_metadata_bp_absence",
    "validate_v10_timeline_events_forbidden",
    "validate_v11_medication_whitelist_and_trajectory",
    "validate_v12_dataset_diversity",
    "build_diversity_fingerprint",
    "validate_chroma_metadata_contract",
    "run_v13_similarity_report",
]
