"""
scripts/check_retrieval_enricher_output.py

Debug utility for inspecting retrieval-enriched text generated by
ingestion.retrieval_enricher.build_retrieval_text().

Run from project root:

    python scripts/check_retrieval_enricher_output.py
    python scripts/check_retrieval_enricher_output.py --patient-id PAT-MOD-001
    python scripts/check_retrieval_enricher_output.py --patient-id PAT-MOD-001 --visit-index 0
    python scripts/check_retrieval_enricher_output.py --source-type doctor_note --source-type lab_result

Purpose:
    Print retrieval text for one patient and one visit so the team can inspect
    whether chunk text is semantically useful before ChromaDB ingestion.

Ownership note:
    This script is only a debug wrapper. The enrichment implementation lives in
    ingestion/retrieval_enricher.py and should be reviewed by the ingestion/RAG
    owner unless Ahmed explicitly takes responsibility for that module.

Safety:
    - No data mutation.
    - No writes to patient JSON files.
    - No ChromaDB writes.
    - No LLM calls.
    - No medical inference.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Iterable

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from config.constants import JSON_ENCODING, SOURCE_TYPES  # noqa: E402
from config.paths import PATIENTS_DIR  # noqa: E402
from ingestion.retrieval_enricher import build_retrieval_text  # noqa: E402

VISIT_LEVEL_SOURCE_TYPES: tuple[str, ...] = (
    "doctor_note",
    "lab_result",
    "prescription",
)

PATIENT_LEVEL_SOURCE_TYPES: tuple[str, ...] = (
    "allergy",
)

DEFAULT_SOURCE_TYPES: tuple[str, ...] = (
    *VISIT_LEVEL_SOURCE_TYPES,
    *PATIENT_LEVEL_SOURCE_TYPES,
)


def load_patient(patient_id: str, source_dir: Path = PATIENTS_DIR) -> dict[str, Any]:
    """
    Load one patient JSON file from source_dir.

    Args:
        patient_id: Patient ID, for example PAT-MOD-001.
        source_dir: Directory containing PAT-*.json files.

    Returns:
        Patient dictionary.

    Raises:
        FileNotFoundError: If the patient file does not exist.
        ValueError: If the JSON is malformed or not an object.
    """
    patient_path = source_dir / f"{patient_id}.json"

    if not patient_path.exists():
        raise FileNotFoundError(f"Patient file not found: {patient_path}")

    try:
        patient = json.loads(patient_path.read_text(encoding=JSON_ENCODING))
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON in {patient_path}: {exc}") from exc

    if not isinstance(patient, dict):
        raise ValueError(f"Patient JSON must be an object: {patient_path}")

    return patient


def select_visit(patient: dict[str, Any], visit_index: int) -> dict[str, Any]:
    """
    Select one visit by zero-based index.

    Args:
        patient: Patient dictionary.
        visit_index: Zero-based visit index.

    Returns:
        Visit dictionary.

    Raises:
        ValueError: If visits is missing/invalid or index is out of range.
    """
    visits = patient.get("visits")

    if not isinstance(visits, list) or not visits:
        raise ValueError("Patient has no visits to inspect.")

    if visit_index < 0 or visit_index >= len(visits):
        raise ValueError(
            f"visit-index {visit_index} is out of range. "
            f"Patient has {len(visits)} visit(s)."
        )

    visit = visits[visit_index]

    if not isinstance(visit, dict):
        raise ValueError(f"Selected visit at index {visit_index} is not an object.")

    return visit


def normalize_source_types(source_types: Iterable[str]) -> tuple[str, ...]:
    """
    Validate requested source types while preserving order and removing duplicates.
    """
    normalized: list[str] = []
    valid_source_types = set(SOURCE_TYPES)

    for source_type in source_types:
        clean_source_type = str(source_type).strip()

        if not clean_source_type:
            continue

        if clean_source_type not in valid_source_types:
            raise ValueError(
                f"Unsupported source_type {clean_source_type!r}. "
                f"Expected one of: {', '.join(SOURCE_TYPES)}."
            )

        if clean_source_type not in normalized:
            normalized.append(clean_source_type)

    if not normalized:
        raise ValueError("At least one source_type must be provided.")

    return tuple(normalized)


def render_source_type_output(
    *,
    patient: dict[str, Any],
    visit: dict[str, Any],
    source_type: str,
) -> str:
    """
    Build retrieval text for one source type.

    Allergy is patient-level and passes visit=None. Other supported source
    types are visit-level and use the selected visit.
    """
    if source_type in PATIENT_LEVEL_SOURCE_TYPES:
        return build_retrieval_text(
            patient=patient,
            visit=None,
            source_type=source_type,
        )

    return build_retrieval_text(
        patient=patient,
        visit=visit,
        source_type=source_type,
    )


def print_retrieval_outputs(
    *,
    patient: dict[str, Any],
    visit: dict[str, Any],
    source_types: Iterable[str],
) -> None:
    """
    Print retrieval text blocks for selected source types.
    """
    patient_id = patient.get("patient_id", "<unknown-patient-id>")
    visit_id = visit.get("visit_id", "<unknown-visit-id>")
    visit_date = visit.get("visit_date", "<unknown-visit-date>")

    print("\n=== RETRIEVAL ENRICHER DEBUG OUTPUT ===")
    print(f"Patient: {patient_id}")
    print(f"Visit:   {visit_id}")
    print(f"Date:    {visit_date}")

    for source_type in source_types:
        print("\n" + "=" * 80)
        print(source_type)
        print("=" * 80)

        text = render_source_type_output(
            patient=patient,
            visit=visit,
            source_type=source_type,
        )

        print(text)


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        description="Inspect retrieval-enriched text for one patient visit."
    )

    parser.add_argument(
        "--patient-id",
        default="PAT-MOD-001",
        help="Patient ID to inspect. Defaults to PAT-MOD-001.",
    )
    parser.add_argument(
        "--visit-index",
        type=int,
        default=0,
        help="Zero-based visit index to inspect. Defaults to 0.",
    )
    parser.add_argument(
        "--source-dir",
        type=Path,
        default=PATIENTS_DIR,
        help="Directory containing PAT-*.json files. Defaults to data/patients.",
    )
    parser.add_argument(
        "--source-type",
        action="append",
        default=None,
        choices=SOURCE_TYPES,
        help=(
            "Source type to print. Can be repeated. "
            "Defaults to doctor_note, lab_result, prescription, allergy."
        ),
    )

    return parser


def main() -> int:
    """CLI entry point."""
    parser = build_parser()
    args = parser.parse_args()

    requested_source_types = (
        tuple(args.source_type)
        if args.source_type
        else DEFAULT_SOURCE_TYPES
    )

    try:
        source_types = normalize_source_types(requested_source_types)
        patient = load_patient(
            patient_id=args.patient_id,
            source_dir=args.source_dir,
        )
        visit = select_visit(patient, args.visit_index)
        print_retrieval_outputs(
            patient=patient,
            visit=visit,
            source_types=source_types,
        )
    except (FileNotFoundError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
